// The Admin component system (Design System 2.0, Tailwind). Import from '../ui' — never restyle the same thing page by page.
export { AdminShell } from './Shell';
export { PageHeader } from './PageHeader';
export { Button, IconButton } from './Button';
export type { ButtonVariant } from './Button';
export { SectionCard, StatCard, KPICard, StatGrid, KeyValue, Card } from './Cards';
export { DataTable } from './DataTable';
export type { Column } from './DataTable';
export { StatusBadge, HealthBadge, HEALTH_LABEL } from './StatusBadge';
export type { BadgeTone, HealthState } from './StatusBadge';
export { EmptyState, LoadingState, ErrorState } from './States';
export { Skeleton, CardSkeleton, TableSkeleton, ChartSkeleton } from './Skeleton';
export { Input, Select, Textarea, SearchInput, FilterBar, FilterField, DateRangePicker, isRangeReady, PERIOD_OPTIONS } from './Inputs';
export type { DateRangeValue, PeriodKey } from './Inputs';
export { Modal, ConfirmDialog, Drawer } from './Modal';
export { ToastProvider, useToast } from './Toast';
export type { ToastTone } from './Toast';
export { Tabs, Pagination } from './Tabs';
export type { TabItem } from './Tabs';
export { ChartContainer, BarChart, HBarList } from './Charts';
export { Icon } from './icons';
export type { IconName } from './icons';
